//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerKin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class gamerkinEntities : DbContext
    {
        public gamerkinEntities()
            : base("name=gamerkinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<game_assets> game_assets { get; set; }
        public virtual DbSet<game_genre> game_genre { get; set; }
        public virtual DbSet<game_platforms> game_platforms { get; set; }
        public virtual DbSet<game_prices> game_prices { get; set; }
        public virtual DbSet<gamer_games> gamer_games { get; set; }
        public virtual DbSet<gamer_genre_skew> gamer_genre_skew { get; set; }
        public virtual DbSet<gamer> gamers { get; set; }
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<genre> genres { get; set; }
    
        public virtual ObjectResult<game> sp_get_recommended_games(Nullable<int> gamerId, Nullable<int> minRating, Nullable<int> limitTo)
        {
            var gamerIdParameter = gamerId.HasValue ?
                new ObjectParameter("gamerId", gamerId) :
                new ObjectParameter("gamerId", typeof(int));
    
            var minRatingParameter = minRating.HasValue ?
                new ObjectParameter("minRating", minRating) :
                new ObjectParameter("minRating", typeof(int));
    
            var limitToParameter = limitTo.HasValue ?
                new ObjectParameter("limitTo", limitTo) :
                new ObjectParameter("limitTo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<game>("sp_get_recommended_games", gamerIdParameter, minRatingParameter, limitToParameter);
        }
    
        public virtual ObjectResult<game> sp_get_recommended_games(Nullable<int> gamerId, Nullable<int> minRating, Nullable<int> limitTo, MergeOption mergeOption)
        {
            var gamerIdParameter = gamerId.HasValue ?
                new ObjectParameter("gamerId", gamerId) :
                new ObjectParameter("gamerId", typeof(int));
    
            var minRatingParameter = minRating.HasValue ?
                new ObjectParameter("minRating", minRating) :
                new ObjectParameter("minRating", typeof(int));
    
            var limitToParameter = limitTo.HasValue ?
                new ObjectParameter("limitTo", limitTo) :
                new ObjectParameter("limitTo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<game>("sp_get_recommended_games", mergeOption, gamerIdParameter, minRatingParameter, limitToParameter);
        }
    }
}
