//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamerKin
{
    using System;
    using System.Collections.Generic;
    
    public partial class gamer_genre_skew
    {
        public int id { get; set; }
        public Nullable<int> gamer_id { get; set; }
        public Nullable<int> genre_id { get; set; }
        public Nullable<int> skew { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
